Map<String, List<Map<String, dynamic>>> newsData = {
  "MARKET": [
    {
      "img": "https://www.bing.com/th/id/OIP.QurEUPfQ6KKKIyDOTtkbLgHaFj",
      "title": "Tomato Price Rise in Local Market",
      "subtitle": "Due to an unseasonal rainfall pattern and logistic delays, tomato prices have soared by ₹10, reaching ₹40/kg in Mandal Market. Vendors report a sharp drop in fresh stock, and local farmers are struggling to meet the growing demand. The Agricultural Department is monitoring the situation and expects price stabilization within two weeks.",
      "likes": 120,
      "dislikes": 10,
      "comments": 14,
    },
    {
      "img": "https://images.unsplash.com/photo-1508747703725-719777637510?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8b25pb25zfGVufDB8fDB8fHww",
      "title": "Onion Prices Drop After Rainfall",
      "subtitle": "Heavy monsoon rains across the state have led to a bumper onion harvest, resulting in a 15% decrease in market prices. While this has provided temporary relief to consumers, farmers are expressing concern about low selling prices and demand government intervention to ensure fair compensation.",
      "likes": 87,
      "dislikes": 5,
      "comments": 9,
    },
    {
      "img": "https://plus.unsplash.com/premium_photo-1661963447711-27f892ffe292?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFkZHl8ZW58MHx8MHx8fDA%3D",
      "title": "Paddy Selling Price Updated",
      "subtitle": "The Minimum Support Price (MSP) for paddy has been revised to ₹2050 per quintal by the state authorities. This increase comes after several farmer unions demanded better pricing to offset rising input costs. Procurement centers will start accepting produce under the new rate from next week.",
      "likes": 153,
      "dislikes": 12,
      "comments": 21,
    },
    {
      "img": "https://plus.unsplash.com/premium_photo-1664365805083-80ff9ccfde9d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fG1hcmtldHxlbnwwfHwwfHx8MA%3D%3D",
      "title": "Weekly Market Day Announced",
      "subtitle": "The Panchayat has designated every Friday as a village market day. Local sellers can set up stalls for agricultural produce, handicrafts, and homemade items. Officials hope this initiative will boost local economy and help villagers avoid travel to distant mandis.",
      "likes": 44,
      "dislikes": 2,
      "comments": 5,
    },
    {
      "img": "https://plus.unsplash.com/premium_photo-1680125265832-ffaf364a8aca?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGZlcnRpbGl6ZXJzfGVufDB8fDB8fHww",
      "title": "Fertilizer Prices Expected to Rise",
      "subtitle": "Fertilizer companies have indicated a potential 5–10% hike in urea and DAP prices in the upcoming season due to international supply chain issues. Farmers are advised to stock up early or consult agricultural officers for cost-effective alternatives and organic options.",
      "likes": 66,
      "dislikes": 17,
      "comments": 12,
    },
  ],
  "HEALTH": [
    {
      "img": "https://www.bing.com/th/id/OIP.1MW0RjTu6TAJ6IeeEwYJuQHaE8",
      "title": "Seasonal Flu Spreads in Nearby Village",
      "subtitle": "A sudden rise in seasonal flu cases has been reported in the nearby village of Bairampur. Local health officers confirmed 12 mild infections. The community health center urges residents to wear masks, avoid crowded places, and drink warm water. Free check-ups will be held this weekend.",
      "likes": 98,
      "dislikes": 3,
      "comments": 20,
    },
    {
      "img": "https://example.com/health1.jpg",
      "title": "Free Health Camp Scheduled",
      "subtitle": "A comprehensive free health camp will be organized at the Primary Health Centre this Sunday. The services include blood pressure, diabetes, and eye check-ups. Free medicine and consultation will be available for all. Women and elderly are especially encouraged to attend.",
      "likes": 120,
      "dislikes": 1,
      "comments": 15,
    },
    {
      "img": "https://example.com/health2.jpg",
      "title": "COVID Booster Dose Open",
      "subtitle": "Booster dose for COVID-19 is now available at PHCs for adults above 18 years. The vaccine is free of charge under government schemes. Citizens are advised to carry Aadhaar cards and wear masks. Priority will be given to elderly and frontline workers.",
      "likes": 134,
      "dislikes": 4,
      "comments": 24,
    },
    {
      "img": "https://example.com/health3.jpg",
      "title": "Awareness Drive on Dengue",
      "subtitle": "With the onset of the rainy season, dengue cases have become a growing concern. The local health team is conducting awareness drives on mosquito prevention. Villagers are encouraged to keep surroundings clean and use mosquito nets. Insect repellents will be distributed free of cost.",
      "likes": 90,
      "dislikes": 6,
      "comments": 10,
    },
    {
      "img": "https://example.com/health4.jpg",
      "title": "Medical Aid Scheme for BPL Families",
      "subtitle": "Under the new rural health scheme, BPL families can now avail medical support up to ₹5000 annually. The scheme covers minor surgeries, seasonal disease treatment, and diagnostic services. Enrollments are open at the Panchayat office and local PHC.",
      "likes": 112,
      "dislikes": 2,
      "comments": 18,
    },
  ],
  "PANCHAYAT": [
    {
      "img": "https://www.bing.com/th/id/OIP.HVBAQFf5tv650Vo-ujOtUAHaEK",
      "title": "Panchayat Meeting on Water Issues",
      "subtitle": "A public meeting was held at the village school to address water scarcity. Key issues like borewell maintenance, pipeline repairs, and new water tank installations were discussed. Officials urged public participation in maintaining cleanliness near water sources.",
      "likes": 60,
      "dislikes": 2,
      "comments": 11,
    },
    {
      "img": "https://example.com/pan1.jpg",
      "title": "Women’s SHG Loan Approval",
      "subtitle": "Ten Self Help Groups in the village have been sanctioned micro-loans to support their small-scale businesses. This step is part of a larger rural economic empowerment program. SHGs will also undergo skill training for financial literacy and product marketing.",
      "likes": 78,
      "dislikes": 1,
      "comments": 9,
    },
    {
      "img": "https://example.com/pan2.jpg",
      "title": "Drainage Repair Work Starts",
      "subtitle": "The long-pending drainage repair near the market road has finally begun under the MNREGA scheme. The work is expected to improve hygiene in the area and prevent waterlogging. Locals are requested to cooperate during the two-week repair schedule.",
      "likes": 50,
      "dislikes": 3,
      "comments": 6,
    },
    {
      "img": "https://example.com/pan3.jpg",
      "title": "Solar Street Lights Inaugurated",
      "subtitle": "30 solar-powered street lights have been installed across major roads in the village. This is aimed at improving nighttime safety and reducing electricity costs. The inauguration was attended by the local MLA and Panchayat Sarpanch.",
      "likes": 92,
      "dislikes": 4,
      "comments": 13,
    },
    {
      "img": "https://example.com/pan4.jpg",
      "title": "PDS Distribution Rescheduled",
      "subtitle": "The Public Distribution System (PDS) dates have been revised to August 3rd and 4th due to delays in transport. Villagers are advised to carry ration cards and collect supplies within the updated window to avoid crowding and last-minute issues.",
      "likes": 69,
      "dislikes": 5,
      "comments": 8,
    },
  ]
};
